void Show7Analog() {
  oled.clear();
  oled.textSize(1);
  oled.text(0,1,"Black");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  StartTimer();
  beep(1);
  sw_ok_unpress();
  if(ReadTimer()>3000) SetSpeed();
  else{
  Read7Analog();
  RefL3 = L3;
  RefL2 = L2;
  RefL1 = L1;
  RefC = C;
  RefR1 = R1;
  RefR2 = R2;
  RefR3 = R3;
  oled.text(1,0,"L3=%d",L3);
  oled.text(2,0,"L2=%d",L2);
  oled.text(3,0,"L1=%d",L1);
  oled.text(4,0,"C =%d",C);
  oled.text(5,0,"R1=%d",R1);
  oled.text(6,0,"R2=%d",R2);
  oled.text(7,0,"R3=%d",R3);
  //oled.textColor(GLCD_WHITE);
  oled.text(0,9,"White");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(2);
  Read7Analog();
  oled.text(1,8,"L3=%d",L3);
  oled.text(2,8,"L2=%d",L2);
  oled.text(3,8,"L1=%d",L1);
  oled.text(4,8,"C =%d",C);
  oled.text(5,8,"R1=%d",R1);
  oled.text(6,8,"R2=%d",R2);
  oled.text(7,8,"R3=%d",R3);
  //oled.textColor(GREEN);
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(3);
  oled.text(0,14,"Average");
  RefL3 = (RefL3+L3)/2;
  RefL2 = (RefL2+L2)/2;
  RefL1 = (RefL1+L1)/2;
  RefC = (RefC+C)/2;
  RefR1 = (RefR1+R1)/2;
  RefR2 = (RefR2+R2)/2;
  RefR3 = (RefR3+R3)/2;
  oled.text(1,17,"%d",RefL3);
  oled.text(2,17,"%d",RefL2);
  oled.text(3,17,"%d",RefL1);
  oled.text(4,17,"%d",RefC);
  oled.text(5,17,"%d",RefR1);
  oled.text(6,17,"%d",RefR2);
  oled.text(7,17,"%d",RefR3);
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  
  beep(100);
  oled.clear();
  oled.text(0,0," Black");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();  
  beep(0);
  Read2BackAnalog();
  RefBL = BL;
  RefBR = BR;
  oled.text(1,0,"BL=%d",BL);
  oled.text(2,0,"BR=%d",BR);
  oled.text(0,9,"White");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(1);
  Read2BackAnalog();
  oled.text(1,8,"BL=%d",BL);
  oled.text(2,8,"BR=%d",BR);
  oled.text(0,14,"Average");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(2);
  RefBL = (RefBL+BL)/2;
  RefBR = (RefBR+BR)/2;
  oled.text(1,17,"%d",RefBL);
  oled.text(2,17,"%d",RefBR);
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  
  beep(100);
  oled.clear();
  oled.text(1,0," Blue");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(100);
  RefBlue = ReadRGB();
  oled.text(1,0," Blue   = %l",RefBlue);
  oled.text(2,0," Green ");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(100);
  RefGreen = ReadRGB();
  oled.text(2,0," Green  = %l",RefGreen);
  oled.text(3,0," Black  ");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(100);
  RefBlack = ReadRGB();
  oled.text(3,0," Black  = %l",RefBlack);
  oled.text(4,0," White ");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(100);
  RefWhite = ReadRGB();
  oled.text(4,0," White  = %l",RefWhite);
  oled.text(5,0," Yellow ");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(100);
  RefYellow = ReadRGB();
  oled.text(5,0," Yellow = %l",RefYellow);
  oled.text(6,0," Red ");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(100);
  RefRed = ReadRGB();
  oled.text(6,0," Red    = %l",RefRed);
  oled.text(8,0," OK To Start ");
  oled.show();
  sw_ok_unpress();
  Wait_sw_ok_press();
  beep(100);
  }
}
